[package]
name = "renderer_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome" }
warp = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
